package com.lojaagro.estoque_api.entities;
import jakarta.persistence.*;import java.math.*;import java.time.*;import java.util.*;
@Entity @Table(name="pedido_lanchonete",uniqueConstraints=@UniqueConstraint(name="uk_pedido_loja_numero",columnNames={"loja_id","numero"}))
public class PedidoLanchonete {
 @Id private UUID id;@ManyToOne(fetch=FetchType.LAZY,optional=false)@JoinColumn(name="loja_id",nullable=false)private Loja loja;
 @ManyToOne(fetch=FetchType.LAZY,optional=false)@JoinColumn(name="usuario_id",nullable=false)private Usuario usuario;
 @ManyToOne(fetch=FetchType.LAZY)@JoinColumn(name="cliente_id")private Cliente cliente;@ManyToOne(fetch=FetchType.LAZY)@JoinColumn(name="mesa_id")private MesaLanchonete mesa;
 @OneToOne(fetch=FetchType.LAZY)@JoinColumn(name="venda_id")private Venda venda;@Column(nullable=false,length=64)private String assinatura;
 @Column(nullable=false)private long numero;@Enumerated(EnumType.STRING)@Column(nullable=false,length=20)private TipoAtendimento tipo;
 @Enumerated(EnumType.STRING)@Column(nullable=false,length=30)private StatusPedido status=StatusPedido.RECEBIDO;
 @Column(length=80)private String identificacao;@Column(length=20)private String telefone;@Column(length=300)private String endereco;@Column(length=500)private String observacoes;
 @Column(nullable=false,precision=19,scale=2)private BigDecimal subtotal;@Column(nullable=false,precision=19,scale=2)private BigDecimal desconto=BigDecimal.ZERO.setScale(2);@Column(nullable=false,precision=19,scale=2)private BigDecimal total;
 @Column(name="criado_em",nullable=false)private LocalDateTime criadoEm;@Column(name="atualizado_em",nullable=false)private LocalDateTime atualizadoEm;@Column(name="enviado_em")private LocalDateTime enviadoEm;@Column(name="pronto_em")private LocalDateTime prontoEm;@Column(name="finalizado_em")private LocalDateTime finalizadoEm;@Column(name="cancelado_em")private LocalDateTime canceladoEm;@Column(name="motivo_cancelamento",length=300)private String motivoCancelamento;
 @Version@Column(nullable=false)private long versao;
 @OneToMany(mappedBy="pedido",cascade=CascadeType.ALL,orphanRemoval=true)@OrderBy("id ASC")private List<PedidoLanchoneteItem> itens=new ArrayList<>();
 @OneToMany(mappedBy="pedido",cascade=CascadeType.ALL,orphanRemoval=true)private List<PedidoLanchoneteConsumo> consumos=new ArrayList<>();
 protected PedidoLanchonete(){}
 public PedidoLanchonete(UUID id,Loja loja,Usuario usuario,Cliente cliente,MesaLanchonete mesa,String assinatura,long numero,TipoAtendimento tipo,String identificacao,String telefone,String endereco,String observacoes,BigDecimal subtotal,BigDecimal desconto,LocalDateTime agora){this.id=id;this.loja=loja;this.usuario=usuario;this.cliente=cliente;this.mesa=mesa;this.assinatura=assinatura;this.numero=numero;this.tipo=tipo;this.identificacao=limitar(identificacao,80);this.telefone=limitar(telefone,20);this.endereco=limitar(endereco,300);this.observacoes=limitar(observacoes,500);this.subtotal=dinheiro(subtotal);this.desconto=dinheiro(desconto);if(this.desconto.signum()<0||(this.subtotal.signum()>0&&this.desconto.compareTo(this.subtotal)>=0)||(this.subtotal.signum()==0&&this.desconto.signum()>0))throw new IllegalArgumentException("Desconto do pedido inválido.");this.total=this.subtotal.subtract(this.desconto);this.criadoEm=agora;this.atualizadoEm=agora;this.enviadoEm=agora;}
 public void adicionarItem(PedidoLanchoneteItem i){itens.add(i);}public void adicionarConsumo(PedidoLanchoneteConsumo c){consumos.add(c);}
 public void avancar(StatusPedido novo,LocalDateTime agora){if(status==novo)return;if(status.encerrado())throw new IllegalArgumentException("Pedido já encerrado.");boolean permitido=switch(status){case RECEBIDO->novo==StatusPedido.EM_PREPARO||novo==StatusPedido.PRONTO;case EM_PREPARO->novo==StatusPedido.PRONTO;case PRONTO->novo==StatusPedido.SAIU_PARA_ENTREGA;case SAIU_PARA_ENTREGA->false;default->false;};if(!permitido)throw new IllegalArgumentException("Mudança de status inválida.");status=novo;atualizadoEm=agora;if(novo==StatusPedido.PRONTO)prontoEm=agora;}
 public void finalizar(Venda venda,LocalDateTime agora){if(status==StatusPedido.CANCELADO)throw new IllegalArgumentException("Pedido cancelado.");this.venda=venda;status=StatusPedido.FINALIZADO;finalizadoEm=agora;atualizadoEm=agora;}
 public void cancelar(String motivo,LocalDateTime agora){if(status==StatusPedido.CANCELADO)throw new IllegalArgumentException("Pedido já cancelado.");if(motivo==null||motivo.isBlank())throw new IllegalArgumentException("Motivo do cancelamento é obrigatório.");status=StatusPedido.CANCELADO;motivoCancelamento=limitar(motivo,300);canceladoEm=agora;atualizadoEm=agora;}
 private BigDecimal dinheiro(BigDecimal v){return(v==null?BigDecimal.ZERO:v).setScale(2,RoundingMode.HALF_UP);}private String limitar(String v,int m){if(v==null||v.isBlank())return null;String s=v.trim();return s.length()>m?s.substring(0,m):s;}
 public UUID getId(){return id;}public Loja getLoja(){return loja;}public Usuario getUsuario(){return usuario;}public Cliente getCliente(){return cliente;}public MesaLanchonete getMesa(){return mesa;}public Venda getVenda(){return venda;}public String getAssinatura(){return assinatura;}public long getNumero(){return numero;}public TipoAtendimento getTipo(){return tipo;}public StatusPedido getStatus(){return status;}public String getIdentificacao(){return identificacao;}public String getTelefone(){return telefone;}public String getEndereco(){return endereco;}public String getObservacoes(){return observacoes;}public BigDecimal getSubtotal(){return subtotal;}public BigDecimal getDesconto(){return desconto;}public BigDecimal getTotal(){return total;}public LocalDateTime getCriadoEm(){return criadoEm;}public LocalDateTime getAtualizadoEm(){return atualizadoEm;}public LocalDateTime getEnviadoEm(){return enviadoEm;}public LocalDateTime getProntoEm(){return prontoEm;}public LocalDateTime getFinalizadoEm(){return finalizadoEm;}public LocalDateTime getCanceladoEm(){return canceladoEm;}public String getMotivoCancelamento(){return motivoCancelamento;}public List<PedidoLanchoneteItem> getItens(){return itens;}public List<PedidoLanchoneteConsumo> getConsumos(){return consumos;}
}
