ALTER TABLE caixa_sessao ADD COLUMN IF NOT EXISTS total_dinheiro NUMERIC(19,2) NOT NULL DEFAULT 0;
ALTER TABLE caixa_sessao ADD COLUMN IF NOT EXISTS total_estornos_dinheiro NUMERIC(19,2) NOT NULL DEFAULT 0;
