server.port=8081
spring.datasource.url=jdbc:postgresql://dpg-dabguqgu01pc73avj5bg-a.oregon-postgres.render.com/estoque_banco?sslmode=require
spring.datasource.username=estoque_banco_user
spring.datasource.password=MjR5RAXVtNSDjyMz9avxXIC0i4tHF668

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true