server.port=8081
spring.datasource.url=jdbc:postgresql://dpg-d9a0h9naqgkc738utqrg-a.oregon-postgres.render.com/estoquepapai?sslmode=require
spring.datasource.username=estoquepapai_user
spring.datasource.password=57uSYCZr1rQl1g0LoFc92ANRlemKEEzo


spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true